name: trump_card_game
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^6.0.0
  firebase_core: ^0.7.0
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.9
  firebase_auth: ^0.20.0+1
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^4.0.1
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  rxdart: ^0.25.0
  intl: ^0.16.1
  test: any
  font_awesome_flutter: ^8.11.0
  flutter_screenutil: ^4.0.3+1
  flutter_offline: ^0.3.0
  lottie: ^0.7.0+1
  flutter_svg: ^0.18.0
  carousel_slider: ^3.0.0
  shared_preferences: ^0.5.12+4
  shape_of_view: ^1.0.2
  flutter_animator: ^2.1.0
  provider: ^4.3.3
  bot_toast: ^3.0.5
  audioplayers: ^0.17.3

dependency_overrides:
  firebase_core: ^0.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/animations/gifs/
    - assets/animations/lottiefiles/
    - assets/icons/
    - assets/icons/png/
    - assets/icons/svg/
    - assets/images/

  fonts:
    - family: Rapier
      fonts:
        - asset: assets/fonts/Rapier.ttf
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf
    - family: neuropol_x_rg
      fonts:
        - asset: assets/fonts/neuropol_x_rg.ttf

