name: trump_card_game
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.9.1+hotfix.2 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^4.3.0
  firebase_core: ^0.5.2
  flutter_facebook_login: ^1.2.0
  google_sign_in: ^4.0.1+1
  firebase_auth: ^0.8.1+4
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^3.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dependency_overrides:
  firebase_core: ^0.5.2


dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  http: ^0.12.0+2
  rxdart: ^0.25.0
  intl: ^0.16.1
  test: any
  e2e: ^0.7.0+1
  font_awesome_flutter: ^8.8.1
  flutter_screenutil: ^2.1.0
  flutter_offline: "^0.3.0"
  lottie: ^0.6.0
  flutter_svg: ^0.19.0
  carousel_slider: ^2.3.1
  shared_preferences: ^0.5.12+4
  shape_of_view: ^1.0.2
  flutter_animator: ^2.1.0
  provider: ^4.3.2+3

  #assets_audio_player: ^2.0.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/animations/gifs/
    - assets/animations/lottiefiles/
    - assets/icons/
    - assets/icons/png/
    - assets/icons/svg/
    - assets/images/

  fonts:
    - family: Rapier
      fonts:
        - asset: assets/fonts/Rapier.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/Helvetica-Neue.ttf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/Open-Sans.ttf
    - family: PT Serif
      fonts:
        - asset: assets/fonts/PT-Serif.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
    - family: Noto Emoji
      fonts:
        - asset: assets/fonts/NotoEmoji-Regular.ttf
    - family: lovera
      fonts:
        - asset: assets/fonts/lovera.otf
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat_black.ttf
        - asset: assets/fonts/montserrat_bold.ttf
        - asset: assets/fonts/montserrat_extra_bold.ttf
        - asset: assets/fonts/montserrat_medium.ttf
        - asset: assets/fonts/montserrat_regular.ttf
        - asset: assets/fonts/montserrat_semi_bold.ttf
        - asset: assets/fonts/montserrat_thin.ttf
        - asset: assets/fonts/montserrat_light.ttf
    - family: moonlite_solid
      fonts:
        - asset: assets/fonts/moonlite_solid.otf
    - family: neuropol_x_rg
      fonts:
        - asset: assets/fonts/neuropol_x_rg.ttf
    - family: rapier_zero
      fonts:
        - asset: assets/fonts/rapier_zero_hollow_italic.ttf
        - asset: assets/fonts/rapier_zero_hollow_x.ttf
        - asset: assets/fonts/rapier_zero_italic.ttf
          weight: 600
    - family: zorque
      fonts:
        - asset: assets/fonts/zorque.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

